// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getDatabase, ref, set } from "firebase/database";

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSyBOEZfg6t_Xkzp1r0nA4UtD6iVTFWZlqKo",
  authDomain: "notes-fb8df.firebaseapp.com",
  databaseURL: "https://notes-fb8df-default-rtdb.asia-southeast1.firebasedatabase.app/",
  projectId: "notes-fb8df",
  storageBucket: "notes-fb8df.appspot.com",
  messagingSenderId: "492619595819",
  appId: "1:492619595819:web:9a5ca0bd00981f6eeeea6e",
  measurementId: "G-REZPSD3HP6"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const db = getDatabase(app);

var phrases = [
  { phrase: 'Have you ever ___ to a foreign country?', correctVerb: 'been' },
  { phrase: 'Have you already ___ your breakfast today?', correctVerb: 'had' },
  { phrase: 'Have you ever ___ lost in a city?', correctVerb: 'gotten' },
  { phrase: 'Have you ever ___ skydiving?', correctVerb: 'gone' },
  { phrase: 'Have you ever ___ a strange food?', correctVerb: 'tried' },
  { phrase: 'Have you already ___ your summer plans?', correctVerb: 'made' },
  { phrase: 'Have you ever ___ an entire day just watching TV?', correctVerb: 'spent' },
  { phrase: 'Have you ever ___ running in a marathon?', correctVerb: 'considered' },
  { phrase: 'Have you already ___ all your emails today?', correctVerb: 'checked' },
  { phrase: 'Have you ever ___ a selfie with a celebrity?', correctVerb: 'taken' },
  { phrase: 'Have you ever ___ your keys inside the car?', correctVerb: 'left' },
  { phrase: 'Have you already ___ your bed today?', correctVerb: 'made' },
  { phrase: 'Have you ever ___ all night to finish a project?', correctVerb: 'stayed up' },
  { phrase: 'Have you ever ___ a bike?', correctVerb: 'ridden' },
  { phrase: 'Have you ever ___ your phone in a taxi?', correctVerb: 'forgotten' },
  { phrase: 'Have you already ___ the garbage out?', correctVerb: 'taken' },
  { phrase: 'Have you ever ___ at a karaoke bar?', correctVerb: 'sung' },
  { phrase: 'Have you ever ___ to fix something and made it worse?', correctVerb: 'tried' },
  { phrase: 'Have you already ___ your workout today?', correctVerb: 'done' },
  { phrase: 'Have you ever ___ someone else’s drink by mistake?', correctVerb: 'drunk' },
  { phrase: 'Have you ever ___ the wrong bus or train?', correctVerb: 'taken' },
  { phrase: 'Have you already ___ a haircut this month?', correctVerb: 'gotten' },
  { phrase: 'Have you ever ___ a surprise party for someone?', correctVerb: 'organized' },
  { phrase: 'Have you ever ___ a musical instrument?', correctVerb: 'played' },
  { phrase: 'Have you ever ___ a language course abroad?', correctVerb: 'taken' },
  { phrase: 'Have you already ___ your taxes for this year?', correctVerb: 'done' },
  { phrase: "Have you ever ___ someone's name in the middle of a conversation?", correctVerb: 'forgotten' },
  { phrase: 'Have you ever ___ a weird dream and remembered it?', correctVerb: 'had' },
  { phrase: 'Have you already ___ your laundry this week?', correctVerb: 'done' },
  { phrase: 'Have you ever ___ a cooking class?', correctVerb: 'taken' },
  { phrase: 'Have you ever ___ a book in one sitting?', correctVerb: 'read' },
  { phrase: 'Have you already ___ your dinner tonight?', correctVerb: 'had' },
  { phrase: 'Have you ever ___ an all-nighter for a test?', correctVerb: 'pulled' },
  { phrase: 'Have you ever ___ a speech in front of a large audience?', correctVerb: 'given' },
  { phrase: 'Have you ever ___ a famous landmark?', correctVerb: 'visited' },
  { phrase: 'Have you already ___ your morning coffee?', correctVerb: 'had' },
  { phrase: 'Have you ever ___ your credit card in an ATM?', correctVerb: 'forgotten' },
  { phrase: 'Have you ever ___ a star in the sky and made a wish?', correctVerb: 'seen' },
  { phrase: "Have you already ___ a doctor's appointment this year?", correctVerb: 'had' },
  { phrase: 'Have you ever ___ an embarrassing moment at work?', correctVerb: 'had' },
  { phrase: 'Have you ever ___ your wallet at home?', correctVerb: 'forgotten' },
  { phrase: 'Have you already ___ to vote in the latest election?', correctVerb: 'gone' },
  { phrase: 'Have you ever ___ someone else’s secret?', correctVerb: 'kept' },
  { phrase: 'Have you ever ___ yoga?', correctVerb: 'tried' },
  { phrase: 'Have you ever ___ in a car accident?', correctVerb: 'been' },
  { phrase: 'Have you already ___ the news today?', correctVerb: 'read' },
  { phrase: 'Have you ever ___ a pet?', correctVerb: 'had' },
  { phrase: 'Have you ever ___ your shoes while they were still on?', correctVerb: 'tied' },
  { phrase: 'Have you already ___ your teeth today?', correctVerb: 'brushed' },
  { phrase: 'Have you ever ___ a wild animal up close?', correctVerb: 'seen' },
  { phrase: 'Have you ever ___ a ghost or something supernatural?', correctVerb: 'seen' },
  { phrase: 'Have you already ___ a book this week?', correctVerb: 'read' },
  { phrase: 'Have you ever ___ on a blind date?', correctVerb: 'been' },
  { phrase: 'Have you ever ___ all the way through a horror movie?', correctVerb: 'made it' },
  { phrase: 'Have you ever ___ out of an airplane or helicopter?', correctVerb: 'jumped' },
  { phrase: 'Have you already ___ your shopping for this week?', correctVerb: 'done' },
  { phrase: 'Have you ever ___ a lie to get out of a situation?', correctVerb: 'told' },
  { phrase: 'Have you ever ___ to a concert alone?', correctVerb: 'gone' },
  { phrase: 'Have you already ___ your bags for your trip?', correctVerb: 'packed' },
  { phrase: 'Have you ever ___ a random act of kindness?', correctVerb: 'performed' },
  { phrase: 'Have you ever ___ a prank on someone?', correctVerb: 'played' },
  { phrase: 'Have you already ___ your lunch today?', correctVerb: 'eaten' },
  { phrase: 'Have you ever ___ caught in a rain without an umbrella?', correctVerb: 'been' },
  { phrase: 'Have you ever ___ scuba diving?', correctVerb: 'gone' },
  { phrase: 'Have you ever ___ stuck in an elevator?', correctVerb: 'been' },
  { phrase: 'Have you already ___ your dinner reservations?', correctVerb: 'made' },
  { phrase: 'Have you ever ___ a contest?', correctVerb: 'won' },
  { phrase: 'Have you ever ___ an exotic fruit?', correctVerb: 'tasted' },
  { phrase: 'Have you already ___ your friends this week?', correctVerb: 'seen' },
  { phrase: 'Have you ever ___ a strange coincidence?', correctVerb: 'experienced' },
  { phrase: 'Have you ever ___ to a movie premiere?', correctVerb: 'been' },
  { phrase: 'Have you already ___ up your room today?', correctVerb: 'cleaned' },
  { phrase: 'Have you ever ___ in a foreign language?', correctVerb: 'dreamt' },
  { phrase: 'Have you ever ___ in love at first sight?', correctVerb: 'believed' },
  { phrase: 'Have you ever ___ a difficult decision to make?', correctVerb: 'had' },
  { phrase: 'Have you already ___ your morning walk or run today?', correctVerb: 'had' },
  { phrase: 'Have you ever ___ the sunrise at the beach?', correctVerb: 'seen' },
  { phrase: 'Have you ever ___ something valuable?', correctVerb: 'lost' },
  { phrase: 'Have you already ___ this month’s rent or mortgage?', correctVerb: 'paid' },
  { phrase: 'Have you ever ___ a crush on a fictional character?', correctVerb: 'had' },
  { phrase: 'Have you ever ___ to a theme park?', correctVerb: 'been' },
  { phrase: 'Have you already ___ the new episode of your favorite show?', correctVerb: 'watched' },
  { phrase: 'Have you ever ___ mistaken for someone else?', correctVerb: 'been' },
  { phrase: "Have you ever ___ someone who didn't recognize you?", correctVerb: 'met' },
  { phrase: 'Have you ever ___ hiking on a mountain?', correctVerb: 'gone' },
  { phrase: 'Have you already ___ this week’s chores?', correctVerb: 'completed' },
  { phrase: 'Have you ever ___ a surprise that wasn’t really a surprise?', correctVerb: 'planned' },
  { phrase: 'Have you ever ___ your phone while it was charging?', correctVerb: 'used' },
  { phrase: 'Have you already ___ your gym session today?', correctVerb: 'completed' },
  { phrase: 'Have you ever ___ a goal that you set for yourself?', correctVerb: 'achieved' },
  { phrase: 'Have you ever ___ a live TV show?', correctVerb: 'attended' },
  { phrase: 'Have you already ___ your plants today?', correctVerb: 'watered' },
  { phrase: 'Have you ever ___ a rainbow?', correctVerb: 'seen' },
  { phrase: 'Have you ever ___ on stage in front of people?', correctVerb: 'been' },
  { phrase: 'Have you ever ___ a letter to the editor?', correctVerb: 'written' },
  { phrase: 'Have you already ___ to your family today?', correctVerb: 'talked' },
  { phrase: "Have you ever ___ a secret you wish you hadn't?", correctVerb: 'kept' },
  { phrase: 'Have you ever ___ a shooting star?', correctVerb: 'seen' },
  { phrase: 'Have you already ___ a walk in the park today?', correctVerb: 'taken' },
  { phrase: 'Have you ever ___ something from a restaurant?', correctVerb: 'stolen' },
  { phrase: 'Have you ever ___ the Northern Lights?', correctVerb: 'seen' },
  { phrase: 'Have you already ___ your lunch today?', correctVerb: 'eaten' },
  { phrase: 'Have you ever ___ a book that made you cry?', correctVerb: 'read' },
  { phrase: 'Have you ever ___ a cooking recipe from the internet?', correctVerb: 'chosen' },
  { phrase: 'Have you already ___ your friends this week?', correctVerb: 'met' },
  { phrase: 'Have you ever ___ a dog?', correctVerb: 'owned' },
  { phrase: 'Have you ever ___ lost while traveling?', correctVerb: 'gotten' },
  { phrase: 'Have you already ___ your hair today?', correctVerb: 'done' },
  { phrase: 'Have you ever ___ the sunrise at the beach?', correctVerb: 'seen' },
  { phrase: 'Have you ever ___ in a band?', correctVerb: 'been' },
  { phrase: 'Have you ever ___ something you regret?', correctVerb: 'said' },
  { phrase: 'Have you already ___ a book this month?', correctVerb: 'read' },
  { phrase: 'Have you ever ___ a mountain?', correctVerb: 'climbed' },
  { phrase: 'Have you ever ___ someone a surprise gift?', correctVerb: 'given' },
  { phrase: 'Have you already ___ your car?', correctVerb: 'driven' },
  { phrase: 'Have you ever ___ something unusual?', correctVerb: 'found' },
  { phrase: 'Have you ever ___ in a foreign language?', correctVerb: 'spoken' },
  { phrase: 'Have you already ___ the trash out?', correctVerb: 'taken' },
  { phrase: 'Have you ever ___ a strange dream?', correctVerb: 'had' },
  { phrase: 'Have you ever ___ a song?', correctVerb: 'written' },
  { phrase: 'Have you ever ___ a museum?', correctVerb: 'visited' },
  { phrase: 'Have you already ___ your phone today?', correctVerb: 'charged' },
  { phrase: 'Have you ever ___ a new skill?', correctVerb: 'learned' },
  { phrase: 'Have you ever ___ someone by their nickname?', correctVerb: 'known' },
  { phrase: 'Have you already ___ to the latest hit song?', correctVerb: 'listened' },
  { phrase: 'Have you ever ___ your way in a foreign city?', correctVerb: 'found' },
  { phrase: 'Have you ever ___ someone from a different culture?', correctVerb: 'met' },
  { phrase: 'Have you already ___ a meal today?', correctVerb: 'cooked' },
  { phrase: 'Have you ever ___ on a roller coaster?', correctVerb: 'been' },
  { phrase: 'Have you ever ___ a horse?', correctVerb: 'ridden' },
  { phrase: 'Have you ever ___ your keys?', correctVerb: 'lost' },
  { phrase: 'Have you already ___ your homework?', correctVerb: 'done' },
  { phrase: 'Have you ever ___ a wild animal?', correctVerb: 'seen' },
  { phrase: "Have you ever ___ a new year's resolution?", correctVerb: 'made' },
  { phrase: 'Have you already ___ a new movie this week?', correctVerb: 'seen' },
  { phrase: 'Have you ever ___ in the rain?', correctVerb: 'danced' },
  { phrase: 'Have you ever ___ a secret garden?', correctVerb: 'found' },
  { phrase: 'Have you already ___ to a new podcast?', correctVerb: 'listened' },
  { phrase: 'Have you ever ___ under the stars?', correctVerb: 'slept' },
  { phrase: 'Have you ever ___ a marathon?', correctVerb: 'run' },
  { phrase: 'Have you ever ___ abroad?', correctVerb: 'been' },
  { phrase: 'Have you already ___ dinner?', correctVerb: 'eaten' },
  { phrase: 'Have you ever ___ a marathon?', correctVerb: 'run' },
  { phrase: 'Have you ever ___ in love at first sight?', correctVerb: 'fallen' },
  { phrase: 'Have you already ___ your emails today?', correctVerb: 'checked' },
  { phrase: 'Have you ever ___ caught in the rain without an umbrella?', correctVerb: 'gotten' },
  { phrase: 'Have you ever ___ a bone?', correctVerb: 'broken' },
  { phrase: 'Have you already ___ your parents today?', correctVerb: 'spoken to' },
  { phrase: 'Have you ever ___ an all-nighter?', correctVerb: 'pulled' },
  { phrase: 'Have you ever ___ lost in a new city?', correctVerb: 'gotten' },
  { phrase: 'Have you already ___ your bills this month?', correctVerb: 'paid' },
  { phrase: 'Have you ever ___ a speech in front of a crowd?', correctVerb: 'given' },
  { phrase: 'Have you ever ___ the Eiffel Tower?', correctVerb: 'seen' },
  { phrase: 'Have you already ___ this year’s taxes?', correctVerb: 'done' },
  { phrase: 'Have you ever ___ a strange food?', correctVerb: 'eaten' },
  { phrase: 'Have you ever ___ to a live concert?', correctVerb: 'been' },
  { phrase: 'Have you already ___ the grocery shopping?', correctVerb: 'done' },
  { phrase: 'Have you ever ___ a surprise party?', correctVerb: 'thrown' },
  { phrase: 'Have you ever ___ skydiving?', correctVerb: 'gone' },
  { phrase: 'Have you ever ___ a job interview?', correctVerb: 'had' },
  { phrase: 'Have you already ___ your hair today?', correctVerb: 'done' },
  { phrase: 'Have you ever ___ a public bus?', correctVerb: 'taken' },
  { phrase: 'Have you ever ___ a rare animal in the wild?', correctVerb: 'seen' },
  { phrase: 'Have you already ___ your workout for today?', correctVerb: 'done' },
  { phrase: 'Have you ever ___ on a motorcycle?', correctVerb: 'ridden' },
  { phrase: 'Have you ever ___ a lost valuable item?', correctVerb: 'found' },
  { phrase: 'Have you already ___ to the new song from your favorite artist?', correctVerb: 'listened' },
  { phrase: 'Have you ever ___ a sunset from a mountaintop?', correctVerb: 'seen' },
  { phrase: 'Have you ever ___ a professional sports game?', correctVerb: 'attended' },
  { phrase: 'Have you ever ___ a celebrity in person?', correctVerb: 'met' },
  { phrase: 'Have you already ___ your bedroom today?', correctVerb: 'cleaned' },
  { phrase: 'Have you ever ___ a magic trick?', correctVerb: 'done' },
  { phrase: 'Have you ever ___ a snake in the wild?', correctVerb: 'seen' },
  { phrase: 'Have you already ___ your breakfast?', correctVerb: 'eaten' },
  { phrase: 'Have you ever ___ a photograph of a famous landmark?', correctVerb: 'taken' },
  { phrase: 'Have you ever ___ out of a moving vehicle?', correctVerb: 'jumped' },
  { phrase: 'Have you already ___ your daily walk?', correctVerb: 'taken' },
  { phrase: 'Have you ever ___ a mountain?', correctVerb: 'climbed' },
  { phrase: 'Have you ever ___ an expensive piece of jewelry?', correctVerb: 'lost' },
  { phrase: 'Have you ever ___ a ghost?', correctVerb: 'seen' },
  { phrase: 'Have you already ___ to your best friend today?', correctVerb: 'spoken' },
  { phrase: 'Have you ever ___ your favorite book?', correctVerb: 'read' },
  { phrase: 'Have you ever ___ a secret for a long time?', correctVerb: 'kept' },
  { phrase: 'Have you already ___ the latest news?', correctVerb: 'read' },
  { phrase: 'Have you ever ___ a foreign language?', correctVerb: 'learned' },
  { phrase: 'Have you ever ___ a scary movie alone?', correctVerb: 'watched' },
  { phrase: 'Have you already ___ dinner?', correctVerb: 'made' },
  { phrase: 'Have you ever ___ a song in a karaoke?', correctVerb: 'sung' },
  { phrase: 'Have you ever ___ in a strange place?', correctVerb: 'slept' },
  { phrase: 'Have you ever ___ a pet?', correctVerb: 'had' },
  { phrase: 'Have you already ___ your morning coffee?', correctVerb: 'had' },
  { phrase: 'Have you ever ___ a car?', correctVerb: 'driven' },
  { phrase: 'Have you ever ___ a campfire?', correctVerb: 'built' },
  { phrase: 'Have you already ___ a shower today?', correctVerb: 'taken' },
  { phrase: 'Have you ever ___ a DIY project?', correctVerb: 'done' },
  { phrase: 'Have you ever ___ a painting?', correctVerb: 'done' },
  { phrase: 'Have you already ___ the latest episode of your favorite show?', correctVerb: 'watched' },
  { phrase: 'Have you ever ___ a letter in another language?', correctVerb: 'written' },
  { phrase: 'Have you ever ___ a promise?', correctVerb: 'broken' },
  { phrase: 'Have you ever ___ a bike?', correctVerb: 'ridden' },
  { phrase: 'Have we not ___ each other before?', correctVerb: 'seen' },
  { phrase: 'Has he ___ been honest with you?', correctVerb: 'always' },
  { phrase: 'Has she ___ mentioned anything about moving?', correctVerb: 'ever' },
  { phrase: 'Have you ___ considered living abroad?', correctVerb: 'ever' },
  { phrase: 'Has the company ___ failed to deliver on its promises?', correctVerb: 'ever' },
  { phrase: 'Have they ___ had problems with their neighbors?', correctVerb: 'ever' },
  { phrase: 'Has she ___ not completed a project on time?', correctVerb: 'ever' },
  { phrase: 'Have I not ___ you about this?', correctVerb: 'told' },
  { phrase: 'Has he ___ been late to work?', correctVerb: 'ever' },
  { phrase: 'Have we ___ met before?', correctVerb: 'ever' },
  { phrase: 'Has the team ___ missed a deadline?', correctVerb: 'ever' },
  { phrase: 'Has she ___ told you why she left her last job?', correctVerb: 'ever' },
  { phrase: 'Have you ___ felt like you were in danger?', correctVerb: 'ever' },
  { phrase: 'Has he ___ mentioned me in any of his conversations?', correctVerb: 'ever' },
  { phrase: 'Have they ___ experienced a natural disaster?', correctVerb: 'ever' },
  { phrase: 'Has the organization ___ failed to meet its goals?', correctVerb: 'ever' },
  { phrase: 'Have you ___ been accused of something you didn’t do?', correctVerb: 'ever' },
  { phrase: 'Has she ___ not met her sales targets?', correctVerb: 'ever' },
  { phrase: 'Have we not ___ this issue before?', correctVerb: 'discussed' },
  { phrase: 'Has he ___ regretted a decision he made?', correctVerb: 'ever' },
  { phrase: 'Has it ___ rained this much before?', correctVerb: 'ever' },
  { phrase: 'Have you ___ had this much responsibility?', correctVerb: 'ever' },
  { phrase: 'Has she ___ failed a test?', correctVerb: 'ever' },
  { phrase: 'Have we ___ overlooked a major issue?', correctVerb: 'ever' },
  { phrase: 'Has the government ___ not delivered on its promises?', correctVerb: 'ever' },
  { phrase: 'Have they ___ missed a flight?', correctVerb: 'ever' },
  { phrase: 'Has he ___ not shown up for a meeting?', correctVerb: 'ever' },
  { phrase: 'Have you ___ not fulfilled a commitment?', correctVerb: 'ever' },
  { phrase: 'Has it ___ been this cold in May?', correctVerb: 'ever' },
  { phrase: 'Have they ___ had to deal with such a situation?', correctVerb: 'ever' },
  { phrase: 'Has she ___ forgotten to call you?', correctVerb: 'ever' },
  { phrase: 'Have I not ___ you that before?', correctVerb: 'told' },
  { phrase: 'Has he ___ been to Europe?', correctVerb: 'ever' },
  { phrase: 'Have they ___ performed in front of a large audience?', correctVerb: 'ever' },
  { phrase: 'Has the project ___ been on schedule?', correctVerb: 'ever' },
  { phrase: 'Have you ___ regretted a decision you made?', correctVerb: 'ever' },
  { phrase: 'Has she ___ missed a deadline?', correctVerb: 'ever' },
  { phrase: 'Have we not ___ this problem in the past?', correctVerb: 'faced' },
  { phrase: 'Has he ___ forgotten your birthday?', correctVerb: 'ever' },
  { phrase: 'Has it ___ been this difficult to find a job?', correctVerb: 'ever' },
  { phrase: 'Have you ___ been to a country where you didn’t speak the language?', correctVerb: 'ever' },
  { phrase: 'Has she ___ not met your expectations?', correctVerb: 'ever' },
  { phrase: 'Have we not ___ this song before?', correctVerb: 'heard' },
  { phrase: 'Has he ___ doubted his abilities?', correctVerb: 'ever' },
  { phrase: 'Has it ___ taken this long to get approved?', correctVerb: 'ever' },
  { phrase: 'Have you ___ been so overwhelmed?', correctVerb: 'ever' },
  { phrase: 'Has she ___ disappointed you?', correctVerb: 'ever' },
  { phrase: 'Have we not ___ this topic in our previous meetings?', correctVerb: 'covered' },
  { phrase: 'Has he ___ missed a payment?', correctVerb: 'ever' },
  { phrase: 'Has it ___ been so difficult to get a reservation?', correctVerb: 'ever' },
  { phrase: 'Have you ___ encountered such a difficult customer?', correctVerb: 'ever' },
  { phrase: 'Has she ___ failed to deliver a project on time?', correctVerb: 'ever' },
  { phrase: 'Have we not ___ such a challenge before?', correctVerb: 'faced' },
  { phrase: 'Has he ___ had doubts about his career?', correctVerb: 'ever' },
  { phrase: 'Has it ___ taken so long to receive a response?', correctVerb: 'ever' },
  { phrase: 'Have they ___ experienced such a severe storm?', correctVerb: 'ever' },
  { phrase: 'Has she ___ not been able to answer a question in class?', correctVerb: 'ever' },
  { phrase: 'Have I not ___ this point clear?', correctVerb: 'made' },
  { phrase: 'Has he ___ not responded to your message?', correctVerb: 'ever' },
  { phrase: 'Has it ___ been this hot in the summer?', correctVerb: 'ever' },
  { phrase: 'Have you ___ missed an important event because you were sick?', correctVerb: 'ever' },
  { phrase: 'Has she ___ failed to meet your standards?', correctVerb: 'ever' },
  { phrase: 'Have we not ___ this conversation before?', correctVerb: 'had' },
  { phrase: 'Has he ___ questioned his decision?', correctVerb: 'ever' },
  { phrase: 'Has it ___ taken this long for a package to arrive?', correctVerb: 'ever' },
  { phrase: 'Have they ___ encountered such a situation?', correctVerb: 'ever' },
  { phrase: 'Has she ___ forgotten an important date?', correctVerb: 'ever' },
  { phrase: 'Have I not ___ my opinion clear?', correctVerb: 'made' },
  { phrase: 'Has he ___ not been able to answer a question?', correctVerb: 'ever' },
  { phrase: 'Has it ___ been this crowded here?', correctVerb: 'ever' },
  { phrase: 'Have you ___ felt out of place?', correctVerb: 'ever' },
  { phrase: 'Has she ___ failed to keep a promise?', correctVerb: 'ever' },
  { phrase: 'Have we not ___ this issue previously?', correctVerb: 'addressed' },
  { phrase: 'Has he ___ questioned his beliefs?', correctVerb: 'ever' },
  { phrase: 'Has it ___ taken this long to get an appointment?', correctVerb: 'ever' },
  { phrase: 'Have they ___ dealt with such difficult customers?', correctVerb: 'ever' },
  { phrase: 'Has she ___ not been able to solve a problem?', correctVerb: 'ever' },
  { phrase: 'Have I not ___ my appreciation for your work?', correctVerb: 'expressed' },
  { phrase: 'Has he ___ missed a flight?', correctVerb: 'ever' },
  { phrase: 'Has it ___ been this noisy in the neighborhood?', correctVerb: 'ever' },
  { phrase: 'Have the results ___ announced yet?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she was in love with him?', correctVerb: 'admitted' },
  { phrase: 'Has your name ___ on the list?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he will be late?', correctVerb: 'said' },
  { phrase: 'Have the flowers ___ watered today?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she didn’t enjoy the movie?', correctVerb: 'mentioned' },
  { phrase: 'Have the documents ___ signed yet?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he doesn’t like sushi?', correctVerb: 'told' },
  { phrase: 'Have your parents ___ informed about your grades?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she won’t be able to come to the party?', correctVerb: 'said' },
  { phrase: 'Has the car ___ fixed?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he doesn’t want to continue with the project?', correctVerb: 'stated' },
  { phrase: 'Have the dishes ___ washed?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she misses her hometown?', correctVerb: 'confessed' },
  { phrase: 'Have the windows ___ cleaned?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he enjoys cooking?', correctVerb: 'mentioned' },
  { phrase: 'Has the homework ___ checked?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she is thinking about quitting her job?', correctVerb: 'admitted' },
  { phrase: 'Has the report ___ submitted yet?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he needs a break?', correctVerb: 'stated' },
  { phrase: 'Has your order ___ delivered?', correctVerb: 'been' },
  { phrase: "Has she ___ that she's been feeling tired lately?", correctVerb: 'said' },
  { phrase: 'Have the tickets ___ sold out?', correctVerb: 'been' },
  { phrase: "Has he ___ that he doesn't want to continue the relationship?", correctVerb: 'told' },
  { phrase: 'Have the assignments ___ graded?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she has always wanted to visit France?', correctVerb: 'revealed' },
  { phrase: 'Has the meeting ___ scheduled?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he is considering a career change?', correctVerb: 'mentioned' },
  { phrase: 'Have the clothes ___ washed?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she regrets her decision?', correctVerb: 'admitted' },
  { phrase: 'Has your email ___ replied to?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he wants to start his own business?', correctVerb: 'said' },
  { phrase: 'Have the rooms ___ cleaned?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she has never been to a concert?', correctVerb: 'confessed' },
  { phrase: 'Have the groceries ___ put away?', correctVerb: 'been' },
  { phrase: "Has he ___ that he doesn't like coffee?", correctVerb: 'stated' },
  { phrase: 'Has the presentation ___ prepared?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she is afraid of heights?', correctVerb: 'told' },
  { phrase: 'Has the food ___ served?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he wants to move to another city?', correctVerb: 'mentioned' },
  { phrase: 'Have the bills ___ paid?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she feels homesick?', correctVerb: 'admitted' },
  { phrase: 'Has your application ___ accepted?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he misses his friends?', correctVerb: 'said' },
  { phrase: 'Have the invitations ___ sent?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she enjoys painting?', correctVerb: 'revealed' },
  { phrase: 'Has the project ___ completed?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he is tired of his job?', correctVerb: 'confessed' },
  { phrase: 'Have the packages ___ shipped?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she wants to learn a new language?', correctVerb: 'stated' },
  { phrase: 'Has your feedback ___ appreciated?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he is not happy with his current lifestyle?', correctVerb: 'admitted' },
  { phrase: 'Have the payments ___ processed?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she feels lonely?', correctVerb: 'said' },
  { phrase: 'Has the cake ___ baked?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he enjoys playing the guitar?', correctVerb: 'mentioned' },
  { phrase: 'Has the software ___ updated?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she is not interested in dating right now?', correctVerb: 'stated' },
  { phrase: 'Have the books ___ returned to the library?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he wants to go back to school?', correctVerb: 'said' },
  { phrase: 'Has your refund ___ processed?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she has been feeling stressed?', correctVerb: 'confessed' },
  { phrase: 'Have the repairs ___ finished?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he feels overwhelmed?', correctVerb: 'admitted' },
  { phrase: 'Has the room ___ booked?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she likes to read?', correctVerb: 'revealed' },
  { phrase: 'Has the work ___ done?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he has been feeling sick?', correctVerb: 'told' },
  { phrase: 'Have the bags ___ packed?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she likes to travel?', correctVerb: 'said' },
  { phrase: 'Has your question ___ answered?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he is worried about the future?', correctVerb: 'admitted' },
  { phrase: 'Have the tests ___ graded?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she has a dog?', correctVerb: 'told' },
  { phrase: 'Has the meeting ___ adjourned?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he likes to run in the morning?', correctVerb: 'revealed' },
  { phrase: 'Has the mail ___ delivered?', correctVerb: 'been' },
  { phrase: 'Has she ___ that she is a vegetarian?', correctVerb: 'said' },
  { phrase: 'Has the laundry ___ done?', correctVerb: 'been' },
  { phrase: 'Has he ___ that he is planning a trip?', correctVerb: 'stated' },
  { phrase: "Have we not ___ this problem once before?", correctVerb: "resolved" },
  { phrase: "Has she ___ lost a valuable item?", correctVerb: "ever" },
  { phrase: "Have you ___ faced a problem you couldn’t solve?", correctVerb: "ever" },
  { phrase: "Has he ___ failed an exam?", correctVerb: "ever" },
  { phrase: "Have they ___ visited a foreign country?", correctVerb: "ever" },
  { phrase: "Has it ___ been this expensive?", correctVerb: "ever" },
  { phrase: "Have we not ___ a similar challenge?", correctVerb: "overcome" },
  { phrase: "Has she ___ not met a deadline?", correctVerb: "ever" },
  { phrase: "Have you ___ forgotten an important meeting?", correctVerb: "ever" },
  { phrase: "Has he ___ been to a concert?", correctVerb: "ever" },
  { phrase: "Have they ___ had a serious illness?", correctVerb: "ever" },
  { phrase: "Has it ___ taken so long to get a promotion?", correctVerb: "ever" },
  { phrase: "Have we not ___ this situation in the past?", correctVerb: "dealt with" },
  { phrase: "Has she ___ not finished her work on time?", correctVerb: "ever" },
  { phrase: "Have you ___ been in a car accident?", correctVerb: "ever" },
  { phrase: "Has he ___ felt so helpless?", correctVerb: "ever" },
  { phrase: "Have they ___ lost a job?", correctVerb: "ever" },
  { phrase: "Has it ___ been this dry in the summer?", correctVerb: "ever" },
  { phrase: "Have we not ___ this matter previously?", correctVerb: "discussed" },
  { phrase: "Has she ___ not prepared for a presentation?", correctVerb: "ever" },
  { phrase: "Have you ___ been lost in a foreign city?", correctVerb: "ever" },
  { phrase: "Has he ___ been caught in a lie?", correctVerb: "ever" },
  { phrase: "Have they ___ visited a national park?", correctVerb: "ever" },
  { phrase: "Has it ___ been this difficult to find a parking space?", correctVerb: "ever" },
  { phrase: "Have we not ___ this misunderstanding before?", correctVerb: "had" },
  { phrase: "Has she ___ forgotten an appointment?", correctVerb: "ever" },
  { phrase: "Have you ___ not been ready for an exam?", correctVerb: "ever" },
  { phrase: "Has he ___ failed to deliver on a promise?", correctVerb: "ever" },
  { phrase: "Have they ___ encountered such difficulties?", correctVerb: "ever" },
  { phrase: "Has it ___ taken this long to repair the roads?", correctVerb: "ever" },
  { phrase: "Have we not ___ this issue last year?", correctVerb: "resolved" },
  { phrase: "Has she ___ missed a flight?", correctVerb: "ever" },
  { phrase: "Have you ___ been stuck in an elevator?", correctVerb: "ever" },
  { phrase: "Has he ___ broken a bone?", correctVerb: "ever" },
  { phrase: "Have they ___ made a huge mistake at work?", correctVerb: "ever" },
  { phrase: "Has it ___ been this difficult to book a flight?", correctVerb: "ever" },
  { phrase: "Have we not ___ such an error in the past?", correctVerb: "corrected" },
  { phrase: "Has she ___ not been selected for a job?", correctVerb: "ever" },
  { phrase: "Have you ___ not handed in an assignment on time?", correctVerb: "ever" },
  { phrase: "Has he ___ not been able to pay a bill?", correctVerb: "ever" },
  { phrase: "Have they ___ lost their passport while traveling?", correctVerb: "ever" },
  { phrase: "Has it ___ taken so long to get a visa?", correctVerb: "ever" },
  { phrase: "Have we not ___ this topic extensively?", correctVerb: "researched" },
  { phrase: "Has she ___ failed to attend a meeting?", correctVerb: "ever" },
  { phrase: "Have you ___ been stranded in a foreign country?", correctVerb: "ever" },
  { phrase: "Has he ___ not been able to finish a task?", correctVerb: "ever" },
  { phrase: "Have they ___ had to evacuate their home?", correctVerb: "ever" },
  { phrase: "Has it ___ been this difficult to rent a house?", correctVerb: "ever" },
  { phrase: "Have we not ___ this conflict before?", correctVerb: "resolved" },
  { phrase: "Has she ___ forgotten a friend’s birthday?", correctVerb: "ever" },
  { phrase: "Have you ___ missed a bus or train?", correctVerb: "ever" },
  { phrase: "Has he ___ failed to recognize someone he knows?", correctVerb: "ever" },
  { phrase: "Have they ___ visited a world heritage site?", correctVerb: "ever" },
  { phrase: "Has it ___ taken so long to get a doctor’s appointment?", correctVerb: "ever" },
  { phrase: "Have we not ___ a similar issue in the past?", correctVerb: "addressed" },
  { phrase: "Has she ___ missed an important email?", correctVerb: "ever" },
  { phrase: "Have you ___ been locked out of your house?", correctVerb: "ever" },
  { phrase: "Has he ___ been unable to help a friend in need?", correctVerb: "ever" },
  { phrase: "Have they ___ had to cancel a trip?", correctVerb: "ever" },
  { phrase: "Has it ___ taken this long to receive a package?", correctVerb: "ever" },
  { phrase: "Have we not ___ this challenge before?", correctVerb: "faced" },
  { phrase: "Has she ___ not been able to attend a class?", correctVerb: "ever" },
  { phrase: "Have you ___ not been able to find something you lost?", correctVerb: "ever" },
  { phrase: "Has he ___ missed an important call?", correctVerb: "ever" },
  { phrase: "Have they ___ had a flight cancelled?", correctVerb: "ever" },
  { phrase: "Has it ___ been this difficult to get a loan?", correctVerb: "ever" },
  { phrase: "Have we not ___ this discussion before?", correctVerb: "had" },
  { phrase: "Has she ___ failed to make a payment?", correctVerb: "ever" },
  { phrase: "Have you ever ___ about your health?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her grades?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our team’s performance?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his job security?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we might be going in the wrong direction?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about the effects of climate change?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her children’s safety?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about the company’s financial stability?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his future?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we may not be prepared enough?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about your diet?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her parents’ health?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our lack of resources?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his lack of experience?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we don’t communicate enough?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about the rising cost of living?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her job satisfaction?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about the impact of our actions?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his relationships?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we might not reach our goals?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about your physical fitness?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her financial security?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about the success of our project?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his career progression?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we might be making a mistake?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about your environmental impact?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her work-life balance?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our competitive position?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his personal development?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we may be overlooking something important?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about your mental health?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her performance at work?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our ability to meet expectations?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his retirement plans?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we might not be doing enough?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about the state of the world?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her ability to handle stress?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our decision-making process?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his level of knowledge?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we might be wasting resources?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about your overall wellbeing?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her leadership skills?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our ability to innovate?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his relationship with his family?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we may not be making the right choices?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about the effects of technology on society?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her self-esteem?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our team dynamics?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his ability to adapt to change?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we might be taking unnecessary risks?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about your level of productivity?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her influence on others?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our public image?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his skills and abilities?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we may not be paying enough attention?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about the future of the planet?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her personal relationships?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our ability to solve problems?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his work ethic?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we might be moving too fast?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about your impact on others?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her personal growth?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our strategic direction?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his financial planning?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we might be ignoring the warning signs?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about your privacy?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her capacity to learn new things?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our ability to handle pressure?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his communication skills?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we might be overlooking opportunities?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about your ability to stay focused?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her ability to meet deadlines?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our capacity for growth?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his ability to manage stress?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we might not be understanding each other?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about your ability to make decisions?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her ability to maintain balance?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our level of cooperation?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his ability to lead others?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we might be missing the bigger picture?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about your ability to manage your time effectively?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her ability to handle responsibility?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our ability to face challenges?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his ability to work in a team?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we might not be setting realistic goals?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about your ability to achieve your goals?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her ability to manage conflict?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our ability to meet customer needs?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his ability to handle failure?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we might not be considering all the options?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about your ability to stay motivated?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her ability to manage her emotions?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our ability to maintain quality?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his ability to meet expectations?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we might not be valuing each other’s contributions?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about your ability to stay positive?", correctVerb: "been concerned" },
  { phrase: "Has she ever ___ about her ability to stay disciplined?", correctVerb: "been concerned" },
  { phrase: "Have we ever ___ about our ability to improve?", correctVerb: "been concerned" },
  { phrase: "Has he ever ___ about his ability to maintain relationships?", correctVerb: "been concerned" },
  { phrase: "Has it ever ___ you that we might be losing sight of our values?", correctVerb: "concerned" },
  { phrase: "Have you ever ___ about your ability to handle uncertainty?", correctVerb: "been concerned" },
  { phrase: "Have you ___ any pets?", correctVerb: "got" },
  { phrase: "Has she ___ about the new regulations?", correctVerb: "known" },
  { phrase: "Have we ___ any feedback from the client?", correctVerb: "got" },
  { phrase: "Has he ___ that you've been promoted?", correctVerb: "known" },
  { phrase: "Has it ___ any upgrades recently?", correctVerb: "got" },
  { phrase: "Have you ___ any new friends at work?", correctVerb: "got" },
  { phrase: "Has she ___ that we're moving offices?", correctVerb: "known" },
  { phrase: "Have we ___ any new customers this month?", correctVerb: "got" },
  { phrase: "Has he ___ about the changes in the team?", correctVerb: "known" },
  { phrase: "Have you ___ any interesting books lately?", correctVerb: "got" },
  { phrase: "Has she ___ about the new project?", correctVerb: "known" },
  { phrase: "Have we ___ any orders from the new supplier?", correctVerb: "got" },
  { phrase: "Has he ___ that you're taking a vacation?", correctVerb: "known" },
  { phrase: "Has it ___ any views?", correctVerb: "got" },
  { phrase: "Have you ___ any good news recently?", correctVerb: "got" },
  { phrase: "Has she ___ about your plans?", correctVerb: "known" },
  { phrase: "Have we ___ any information about the conference?", correctVerb: "got" },
  { phrase: "Has he ___ that we're expecting him?", correctVerb: "known" },
  { phrase: "Has it ___ any updates?", correctVerb: "got" },
  { phrase: "Have you ___ any recommendations for a good restaurant?", correctVerb: "got" },
  { phrase: "Has she ___ about the budget cuts?", correctVerb: "known" },
  { phrase: "Have we ___ any increase in sales?", correctVerb: "got" },
  { phrase: "Has he ___ that we've been waiting for him?", correctVerb: "known" },
  { phrase: "Has it ___ any attention?", correctVerb: "got" },
  { phrase: "Have you ___ any invitations to parties?", correctVerb: "got" },
  { phrase: "Has she ___ about your new job?", correctVerb: "known" },
  { phrase: "Have we ___ any offers for the property?", correctVerb: "got" },
  { phrase: "Has he ___ about the meeting?", correctVerb: "known" },
  { phrase: "Has it ___ any reviews?", correctVerb: "got" },
  { phrase: "Have you ___ any luck finding a new apartment?", correctVerb: "got" },
  { phrase: "Has she ___ about the deadline?", correctVerb: "known" },
  { phrase: "Have we ___ any results from the campaign?", correctVerb: "got" },
  { phrase: "Has he ___ that the report is due tomorrow?", correctVerb: "known" },
  { phrase: "Has it ___ any awards?", correctVerb: "got" },
  { phrase: "Have you ___ any time to relax?", correctVerb: "got" },
  { phrase: "Has she ___ about your achievement?", correctVerb: "known" },
  { phrase: "Have we ___ any feedback from the survey?", correctVerb: "got" },
  { phrase: "Has he ___ about the changes in the schedule?", correctVerb: "known" },
  { phrase: "Has it ___ any problems?", correctVerb: "got" },
  { phrase: "Have you ___ any new hobbies?", correctVerb: "got" },
  { phrase: "Has she ___ about your plans for the weekend?", correctVerb: "known" },
  { phrase: "Have we ___ any replies to our email?", correctVerb: "got" },
  { phrase: "Has he ___ about the resignation?", correctVerb: "known" },
  { phrase: "Has it ___ any maintenance recently?", correctVerb: "got" },
  { phrase: "Have you ___ any opportunities to travel?", correctVerb: "got" },
  { phrase: "Has she ___ about your upcoming trip?", correctVerb: "known" },
  { phrase: "Have we ___ any new members in the team?", correctVerb: "got" },
  { phrase: "Has he ___ about the new policy?", correctVerb: "known" },
  { phrase: "Has it ___ any improvements?", correctVerb: "got" },
  { phrase: "Have you ___ any surprising news?", correctVerb: "got" },
  { phrase: "Has she ___ about the delay?", correctVerb: "known" },
  { phrase: "Have we ___ any sign of progress?", correctVerb: "got" },
  { phrase: "Has he ___ about the surprise party?", correctVerb: "known" },
  { phrase: "Has it ___ any downtime?", correctVerb: "got" },
  { phrase: "Have you ___ any memorable experiences?", correctVerb: "got" },
  { phrase: "Has she ___ about your promotion?", correctVerb: "known" },
  { phrase: "Have we ___ any decline in performance?", correctVerb: "got" },
  { phrase: "Has he ___ about the change in management?", correctVerb: "known" },
  { phrase: "Has it ___ any difficulties?", correctVerb: "got" },
  { phrase: "Have you ___ any interesting emails?", correctVerb: "got" },
  { phrase: "Has she ___ about the new strategy?", correctVerb: "known" },
  { phrase: "Have we ___ any increase in productivity?", correctVerb: "got" },
  { phrase: "Has he ___ that you're moving?", correctVerb: "known" },
  { phrase: "Has it ___ any criticism?", correctVerb: "got" },
  { phrase: "Have you ___ any interesting offers?", correctVerb: "got" },
  { phrase: "Has she ___ about your decision?", correctVerb: "known" },
  { phrase: "Have we ___ any feedback from the presentation?", correctVerb: "got" },
  { phrase: "Has he ___ about the audit?", correctVerb: "known" },
  { phrase: "Has it ___ any issues?", correctVerb: "got" },
  { phrase: "Have you ___ any time to exercise?", correctVerb: "got" },
  { phrase: "Has she ___ about the conference?", correctVerb: "known" },
  { phrase: "Have we ___ any calls about the proposal?", correctVerb: "got" },
  { phrase: "Has he ___ that we're rebranding?", correctVerb: "known" },
  { phrase: "Has it ___ any repairs?", correctVerb: "got" },
  { phrase: "Have you ___ any experience in this field?", correctVerb: "got" },
  { phrase: "Has she ___ about your project?", correctVerb: "known" },
  { phrase: "Have we ___ any response from the media?", correctVerb: "got" },
  { phrase: "Has he ___ about your achievement?", correctVerb: "known" },
  { phrase: "Has it ___ any funding?", correctVerb: "got" },
  { phrase: "Have you ___ any recognition for your work?", correctVerb: "got" },
  { phrase: "Has she ___ about the merger?", correctVerb: "known" },
  { phrase: "Have we ___ any breakthroughs in our research?", correctVerb: "got" },
  { phrase: "Has he ___ about the layoffs?", correctVerb: "known" },
  { phrase: "Has it ___ any endorsements?", correctVerb: "got" },
  { phrase: "Have you ___ any new responsibilities at work?", correctVerb: "got" },
  { phrase: "Has she ___ about the new hire?", correctVerb: "known" },
  { phrase: "Have we ___ any reviews for our product?", correctVerb: "got" },
  { phrase: "Has he ___ that we're relocating?", correctVerb: "known" },
  { phrase: "Has it ___ any complaints?", correctVerb: "got" },
  { phrase: "Have you ___ any chances to explore the city?", correctVerb: "got" },
  { phrase: "Has she ___ about your scholarship?", correctVerb: "known" },
  { phrase: "Have we ___ any milestones in the project?", correctVerb: "got" },
  { phrase: "Has he ___ about the agreement?", correctVerb: "known" },
  { phrase: "Has it ___ any acclaim?", correctVerb: "got" },
  { phrase: "Have you ___ any new skills?", correctVerb: "got" },
  { phrase: "Has she ___ about your new hobby?", correctVerb: "known" },
  { phrase: "Have we ___ any progress in our efforts?", correctVerb: "got" },
  { phrase: "Has he ___ about your retirement?", correctVerb: "known" },
  { phrase: "Has it ___ any interest?", correctVerb: "got" },
  { phrase: "Have you ___ any inspirations recently?", correctVerb: "got" },
];

// Загрузка всех фраз в базу данных Firebase
for (let i = 0; i < phrases.length; i++) {
  set(ref(db, 'phrases/' + i), phrases[i]);
}
